version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
    pull-request-branch-name:
      separator: '-'
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: build
    groups:
      development-dependencies:
        dependency-type: development
        update-types: [minor, patch]
